import { GITHUB_EVENT_PROFILES } from './providers/github/event-profiles'
import { KNOWN_SOURCE_TYPES } from './subscription-sources'

export function commandReference(): string {
  const sources = KNOWN_SOURCE_TYPES.join(', ')
  const githubProfiles = Object.keys(GITHUB_EVENT_PROFILES).sort().join(', ')

  return [
    'Hookrelay quick reference',
    '',
    'Guided setup',
    '  pnpm sink:add <name> <discord|webhook>',
    '      Add a Discord or signed generic webhook sink, then offer to install and sync it',
    '  pnpm sink:rename <old-name> <new-name>',
    '      Safely prepare, switch, and finalize a deployed sink rename',
    '  pnpm sink:secret:rename <sink> <old-secret> <new-secret>',
    '      Change one sink *Env reference without changing its delivery identity',
    '  pnpm sink:retire <name> --manifest <file>',
    '      Stage an unused sink, then finalize after delivery references are clear',
    '  pnpm sub:add <name> <source> [-s <sink>]',
    '      Add a subscription locally, then offer to install, sync, and configure it',
    '  pnpm github:events <name> [-e <profiles>]',
    '      Update or reconcile an existing GitHub webhook event selection',
    '  pnpm sub:retire <name> --manifest <file>',
    '      Disable a subscription, then finalize from a private recovery archive',
    '  pnpm cloudevents:send',
    '      Send a valid signed test event without exposing its URL or HMAC in process arguments',
    '  pnpm sync',
    '      Preview routes.jsonc against production KV',
    '  pnpm sync -y                         [production write]',
    '      Apply the routes.jsonc plan to production KV',
    '  pnpm retention plan',
    '      Compare the managed R2 lifecycle rule with routes.jsonc',
    '  pnpm retention apply                 [production write]',
    '      Preserve unrelated lifecycle rules and apply the managed rule',
    '  pnpm retention verify',
    '      Require the managed lifecycle rule to match exactly',
    '',
    `Sources: ${sources}`,
    'sub:add options: -s/--sink, -b/--base-url, --fallback-url, --email-base, --allow-sender, --primary-link-label, -r/--repo, -e/--events, -y/--yes',
    'github:events options: -e/--events, -y/--yes',
    'retirement options: -m/--manifest, --finalize, -y/--yes; sub:retire also has -r/--routes, -d/--dev-vars, -e/--expected-slug-hash',
    'retention options: -y/--yes (apply only)',
    'GitHub --events defaults to push; recommended and named profiles compose with commas',
    `GitHub profiles: ${githubProfiles}`,
    'GitHub all and manual selections are exclusive',
    '',
    'Optional integrations',
    '  pnpm github:fleet --help',
    '      Manage the dogfooded GitHub repository fleet; see integrations/github-fleet/README.md',
    '  pnpm subscription:fleet --help',
    '      Reconcile externally managed CloudEvents subscriptions; see integrations/subscription-fleet/README.md',
    '',
    'Develop and verify',
    '  pnpm dev                             Start the local Worker',
    '  pnpm test                            Run the test suite',
    '  pnpm test:watch                      Run tests in watch mode',
    '  pnpm typecheck                       Regenerate Worker types and check TypeScript',
    '',
    'Release',
    '  npm version <major|minor|patch>      Check, commit, tag, atomically push, and trigger a draft GitHub Release',
    '      GitHub Actions verifies the tag and prepares generated notes for review',
    '  pnpm retag                          Repair the current version tag before publication [GitHub write]',
    '  pnpm retag --allow-published        Explicitly repair a published release tag [destructive GitHub write]',
    '',
    'Deploy',
    '  pnpm deploy                          Deploy Worker code [production write]',
    '',
    'Low-level',
    '  pnpm new-sub <name> <source>         Print a hash-only subscription stub',
    '',
    'Setup commands write local files before asking about production',
    '-y skips production confirmations; omit it when you want to review each step',
    'Use pnpm <command> -h for full command-specific options',
  ].join('\n')
}

if (import.meta.main) console.log(commandReference())
